### ISSUE TITLE
TSLint warnings

### ISSUE THREAD

**Issue by SteveALee** [joseluisq/hyperapp-starter#1]
After TSLint has finished running  in code I get the following warnings in the output pain

```
[Info  - 12:32:16] Linter is running.
[Info  - 12:32:18] TSLint library loaded from: c:\projects\bass-tools\node_modules\tslint\lib\index.js
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Warning: The 'no-circular-imports' rule requires type information.
Warning: The 'await-promise' rule requires type information.
Warning: The 'no-unused-variable' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'return-undefined' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
Warning: The 'no-unnecessary-type-assertion' rule requires type information.
Warning: The 'strict-type-predicates' rule requires type information.

```

**Comment by joseluisq** [comment]
This warning is related to [tslint-config-standard-plus](https://github.com/joseluisq/tslint-config-standard-plus/issues/1) dependency. Obviously this is an optional dependency in your project but I will fix soon.

**Comment by joseluisq** [comment]
> After TSLint has finished running in code I get the following warnings in the output pain
> 
> [Info  - 12:32:16] Linter is running.
> [Info  - 12:32:18] TSLint library loaded from: c:\projects\bass-tools\node_modules\tslint\lib\index.js
> no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
> Warning: The 'no-circular-imports' rule requires type information.
> Warning: The 'await-promise' rule requires type information.
> Warning: The 'no-unused-variable' rule requires type information.
> Warning: The 'no-use-before-declare' rule requires type information.
> Warning: The 'return-undefined' rule requires type information.
> Warning: The 'no-floating-promises' rule requires type information.
> Warning: The 'no-unnecessary-qualifier' rule requires type information.
> Warning: The 'no-unnecessary-type-assertion' rule requires type information.
> Warning: The 'strict-type-predicates' rule requires type information.

Your warnings appeared because you tried to run TSLint by default without any `--project` option. That's why it works via CLI rather than VS Code TSLint running.
More info at https://github.com/palantir/tslint/issues/3443#issuecomment-341653465
