### ISSUE TITLE
actions type error in test/app.spec.tsx

### ISSUE THREAD

**Issue by SteveALee** [joseluisq/hyperapp-starter#3]
This is a bit weird. Line 25 has a red squiqgle on the actions argument and this error.

```
{
	"resource": "/c:/projects/hyperapp-starter-master/test/app.spec.tsx",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'ActionsType<any, any>' is not assignable to parameter of type 'ActionsType<State, Actions>'.\n  Property 'down' is missing in type 'ActionsType<any, any>'.",
	"source": "ts",
	"startLineNumber": 25,
	"startColumn": 30,
	"endLineNumber": 25,
	"endColumn": 37
}
```

But when I go to definition it is the exported version from `app.tsx'

```
export const actions: ActionsType<State, Actions> = Store.actions
```

So surely everything should line up and be fine? It looks like State and Actions are correctly seen.

**Comment by SteveALee** [comment]
Ah, your tsconfig explicitly excludes test folder

Should be

```
  "include": [
    "src",
    "test"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ],

```

**Comment by joseluisq** [comment]
> But when I go to definition it is the exported version from `app.tsx'
> 
> export const actions: ActionsType<State, Actions> = Store.actions
> So surely everything should line up and be fine? It looks like State and Actions are correctly seen.

Yeah, it's weird because at  https://github.com/joseluisq/hyperapp-starter/blob/187f2b5a4a699325b02a2f4c1958e69b99b05178/src/main.tsx#L1-L5 we have the same definition and I don't see any error.

**Comment by joseluisq** [comment]
> Ah, your tsconfig explicitly excludes test folder
> 
> Should be
> 
>   "include": [
>     "src",
>     "test"
>   ],
>   "exclude": [
>     "dist",
>     "node_modules"
>   ],

You right!

**Comment by joseluisq** [comment]
At the moment, I don't see any error about it.

VS Code: v1.25.1
OS: Linux

![hyperapp-starter in VS Code Linux](https://user-images.githubusercontent.com/1700322/43105447-4307cdc6-8ed5-11e8-99d7-98bc295b849c.png)

I updated `hyperapp-starter` too.

For now, I will close this issue but feel free to open it if you have some related issue.
