### ISSUE TITLE
Problem with @types and components nesting.

### ISSUE THREAD

**Issue by WitoldSlawko** [joseluisq/hyperapp-starter#5]
Hi.
Your repo is great. But I found two main problems:

1) First the @app/types have problem when using npm : npm i && npm build && npm start:
" Cannot create property 'fileName' on string 'Error: Failed to install @app/types.
    at PromiseQueue.install [as process] (/home/wiciu/Code_Projects/Hyperapp/hyperapp-starter/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)'"
and
"hyperapp-starter/src/main.tsx:2:31: Failed to install @app/types."
(although here yarn passes installing, building and app starting processes)

2) Other issue is about nesting components there is TypeScrpt 2605 error :
![hypper_app-nested-components-2](https://user-images.githubusercontent.com/20817587/52533485-c3522280-2d34-11e9-9d2b-ba269f7eaf14.png)
![hypper_app-nested-components](https://user-images.githubusercontent.com/20817587/52533486-c3522280-2d34-11e9-86aa-120e43063964.png)

**Comment by joseluisq** [comment]
> 1. First the @app/types have problem when using npm : npm i && npm build && npm start:
>    " Cannot create property 'fileName' on string 'Error: Failed to install @app/types.
>    at PromiseQueue.install [as process] (/home/wiciu/Code_Projects/Hyperapp/hyperapp-starter/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
>    at 
>    at process._tickCallback (internal/process/next_tick.js:188:7)'"
>    and
>    "hyperapp-starter/src/main.tsx:2:31: Failed to install @app/types."
>    (although here yarn passes installing, building and app starting processes)

This happens due a known issue with `parcel-plugin-typescript`. See [this thread](https://github.com/parcel-bundler/parcel/issues/202#issuecomment-438043672).
One workaround is install a `@babel/preset-typescript` instead.
I will do an update for it.

> 2\. Other issue is about nesting components there is TypeScrpt 2605 error :

Because the project is using Typescript v2.9.2.
For fix that, in your VSCode chose "Select Typescript version" > "Use workspace version (v2.9.2)"

**Comment by joseluisq** [comment]
Check out [v1.0.0](https://github.com/joseluisq/hyperapp-starter/releases/tag/1.0.0)
